from typing import Dict, Any, Optional
from popmely.agent.bot_engine import bot_agent
from popmely.agent.notifier import notifier

def agent_start(
    symbol: str = "XAUUSD",
    timeframe: str = "M15",
    strategy: str = "smc",
    scan_interval: int = 15,
    auto_trade: bool = False,
    risk_percent: float = 1.0,
    rr_ratio: float = 2.0,
    enable_breakeven: bool = True,
    be_trigger_points: float = 300.0
) -> Dict[str, Any]:
    """Start the autonomous AI trading agent background worker."""
    return bot_agent.start(
        symbol=symbol,
        timeframe=timeframe,
        strategy=strategy,
        scan_interval=scan_interval,
        auto_trade=auto_trade,
        risk_percent=risk_percent,
        rr_ratio=rr_ratio,
        enable_breakeven=enable_breakeven,
        be_trigger_points=be_trigger_points
    )

def agent_stop() -> Dict[str, Any]:
    """Stop the background autonomous AI trading agent."""
    return bot_agent.stop()

def agent_status() -> Dict[str, Any]:
    """Get the live status, uptime, scan counts, and signals generated by the autonomous agent."""
    return {
        "status": "success",
        "agent": bot_agent.get_status()
    }

def send_test_alert(message: str = "Test alert from popmely AI trading bot!") -> Dict[str, Any]:
    """Send a test notification to Telegram / configured Webhook."""
    res = notifier.send_telegram(f"🔔 <b>[TEST ALERT]</b>\n\n{message}")
    return res

def send_telegram_message(
    message: str,
    chat_id: Optional[str] = None,
    parse_mode: str = "HTML",
    token: Optional[str] = None
) -> Dict[str, Any]:
    """Send any custom/freeform message or trading alert to a Telegram chat or channel."""
    if not message:
        return {"status": "error", "message": "Message text cannot be empty"}
    return notifier.send_telegram(message=message, parse_mode=parse_mode, token=token, chat_id=chat_id)

def send_telegram_photo(
    photo_path: str,
    caption: Optional[str] = None,
    chat_id: Optional[str] = None,
    token: Optional[str] = None
) -> Dict[str, Any]:
    """Send a chart image (.png) or screenshot with optional caption directly to Telegram."""
    if not photo_path:
        return {"status": "error", "message": "photo_path is required"}
    return notifier.send_telegram_photo(photo_path=photo_path, caption=caption, token=token, chat_id=chat_id)
